@startuml
set namespaceSeparator ::

class "stimmapp::main.dart::MyApp" {
  +State<MyApp> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::main.dart::MyApp"

class "stimmapp::main.dart::_MyAppState" {
  +AppStateNotifier? appStateNotifier
  -bool _initialized
  -StreamSubscription<User?>? _authSub
  +void initState()
  -dynamic _initAsync()
  -void _onLocaleChanged()
  +dynamic initThemeMode()
  +dynamic initLocale()
  -Locale? _localeFromString()
  +void dispose()
  +Widget build()
}

"stimmapp::main.dart::_MyAppState" o-- "stimmapp::core::notifiers::app_state_notifier.dart::AppStateNotifier"
"stimmapp::main.dart::_MyAppState" o-- "dart::async::StreamSubscription<User>"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::main.dart::_MyAppState"

class "stimmapp::core::functions::messenger_service.dart::MessengerService" {
  -ScaffoldMessengerState _messenger
  +void register()
  +void showSnackBar()
  +void showError()
  +void showSuccess()
  -String _extractErrorMessage()
}

"stimmapp::core::functions::messenger_service.dart::MessengerService" o-- "flutter::src::material::scaffold.dart::ScaffoldMessengerState"

class "stimmapp::core::theme::app_theme.dart::AppTheme" {
  {static} +ThemeData light
  {static} +ThemeData dark
}

"stimmapp::core::theme::app_theme.dart::AppTheme" o-- "flutter::src::material::theme_data.dart::ThemeData"

class "stimmapp::core::theme::app_text_styles.dart::AppTextStyles" {
  {static} +TextStyle titleTealText
  {static} +TextStyle descriptionText
  {static} +String fontFamily
  {static} -double _xxlSize
  {static} -double _xlSize
  {static} -double _lSize
  {static} -double _mSize
  {static} +TextStyle xxl
  {static} +TextStyle xl
  {static} +TextStyle l
  {static} +TextStyle m
  {static} +TextStyle s
  {static} +TextStyle xxlBold
  {static} +TextStyle xlBold
  {static} +TextStyle lBold
  {static} +TextStyle mBold
  {static} +TextStyle sBold
  {static} +TextStyle xxlBlack
  {static} +TextStyle xxlRed
  {static} +TextStyle icons
  {static} +TextStyle iconsXl
  {static} +TextStyle red
}

"stimmapp::core::theme::app_text_styles.dart::AppTextStyles" o-- "flutter::src::painting::text_style.dart::TextStyle"

class "stimmapp::core::theme::app_text_styles.dart::KValue" {
  {static} +String basicLayout
  {static} +String cleanUi
  {static} +String fixBugs
  {static} +String keyConcepts
}

class "stimmapp::core::services::profile_picture_service.dart::ProfilePictureService" {
  {static} +ProfilePictureService instance
  +ValueNotifier<String?> profileUrlNotifier
  +dynamic loadProfileUrl()
  +dynamic setProfileUrl()
  +dynamic uploadProfilePicture()
}

"stimmapp::core::services::profile_picture_service.dart::ProfilePictureService" o-- "stimmapp::core::services::profile_picture_service.dart::ProfilePictureService"
"stimmapp::core::services::profile_picture_service.dart::ProfilePictureService" o-- "flutter::src::foundation::change_notifier.dart::ValueNotifier<String>"

class "stimmapp::core::services::auth_service.dart::AuthService" {
  +FirebaseAuth firebaseAuth
  +User? currentUser
  +Stream<User?> authStateChanges
  +dynamic signIn()
  +dynamic createAccount()
  +dynamic signOut()
  +dynamic resetPassword()
  +dynamic updateUsername()
  +dynamic deleteAccount()
  +dynamic resetPasswordfromCurrentPassword()
}

"stimmapp::core::services::auth_service.dart::AuthService" o-- "firebase_auth::firebase_auth.dart::FirebaseAuth"
"stimmapp::core::services::auth_service.dart::AuthService" o-- "firebase_auth::firebase_auth.dart::User"
"stimmapp::core::services::auth_service.dart::AuthService" o-- "dart::async::Stream<User>"

class "stimmapp::core::firebase::firestore::collections.dart::FirestoreCollections" {
  {static} +String users
}

class "stimmapp::core::firebase::firestore::firestore_service.dart::FirestoreService" {
  -FirebaseFirestore _db
  +FirebaseFirestore instance
  +CollectionReference<T> colRef()
  +DocumentReference<T> docRef()
  +dynamic getDoc()
  +Stream<T?> watchDoc()
  +Stream<List<T>> watchCol()
  +dynamic upsert()
  +dynamic delete()
}

"stimmapp::core::firebase::firestore::firestore_service.dart::FirestoreService" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"

class "stimmapp::core::firebase::firebase_options.dart::DefaultFirebaseOptions" {
  {static} +FirebaseOptions web
  {static} +FirebaseOptions android
  {static} +FirebaseOptions ios
  {static} +FirebaseOptions macos
  {static} +FirebaseOptions windows
  {static} +FirebaseOptions currentPlatform
}

"stimmapp::core::firebase::firebase_options.dart::DefaultFirebaseOptions" o-- "firebase_core_platform_interface::firebase_core_platform_interface.dart::FirebaseOptions"

class "stimmapp::core::notifiers::app_state_notifier.dart::AppState" {
  +bool isDark
  +Locale? locale
}

"stimmapp::core::notifiers::app_state_notifier.dart::AppState" o-- "dart::ui::Locale"

class "stimmapp::core::notifiers::app_state_notifier.dart::AppStateNotifier" {
  -void Function() _update
  -void _updateImpl()
  +void dispose()
}

"stimmapp::core::notifiers::app_state_notifier.dart::AppStateNotifier" o-- "dart::ui::void Function()"
"flutter::src::foundation::change_notifier.dart::ValueNotifier" <|-- "stimmapp::core::notifiers::app_state_notifier.dart::AppStateNotifier"

class "stimmapp::core::notifiers::notifiers.dart::AppData" {
  {static} +ValueNotifier<double> onboardingSlider1Notifier
  {static} +ValueNotifier<double> onboardingSlider2Notifier
  {static} +ValueNotifier<int> onboardingCurrentIndexNotifier
  {static} +ValueNotifier<bool> isAuthConnected
  {static} +ValueNotifier<bool> isConnectedNotifier
  {static} +ValueNotifier<bool> isAppOutdatedNotifier
  {static} +ValueNotifier<int> navBarCurrentIndexNotifier
}

"stimmapp::core::notifiers::notifiers.dart::AppData" o-- "flutter::src::foundation::change_notifier.dart::ValueNotifier<double>"
"stimmapp::core::notifiers::notifiers.dart::AppData" o-- "flutter::src::foundation::change_notifier.dart::ValueNotifier<int>"
"stimmapp::core::notifiers::notifiers.dart::AppData" o-- "flutter::src::foundation::change_notifier.dart::ValueNotifier<bool>"

class "stimmapp::core::errors::error_page.dart::ErrorPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::core::errors::error_page.dart::ErrorPage"

class "stimmapp::core::errors::error_message.dart::ErrorMessage" {
  {static} +String appVersionIsOutdated
  {static} +String mainErrorWidgetStarted
  {static} +String thisIsNotWorking
  {static} +String noLocalDataFound
  {static} +String noLocalDataSaved
}

class "stimmapp::core::di::service_locator.dart::ServiceLocator" {
  {static} -ServiceLocator _instance
  -FirebaseFirestore _firestore
  -FirestoreService _firestoreService
  +FirebaseFirestore firestore
  +FirestoreService firestoreService
  +void init()
  +void setFirestoreForTest()
}

"stimmapp::core::di::service_locator.dart::ServiceLocator" o-- "stimmapp::core::di::service_locator.dart::ServiceLocator"
"stimmapp::core::di::service_locator.dart::ServiceLocator" o-- "cloud_firestore::cloud_firestore.dart::FirebaseFirestore"
"stimmapp::core::di::service_locator.dart::ServiceLocator" o-- "stimmapp::core::firebase::firestore::firestore_service.dart::FirestoreService"

class "stimmapp::core::data::models::user.dart::User" {
  +String uid
  +List<String> signedPetitions
  +List<String> votedPolls
  +User copyWith()
  {static} +User fromFirestore()
  {static} +Map<String, Object?> toFirestore()
}

class "stimmapp::core::data::models::user_profile.dart::UserProfile" {
  +String uid
  +String? displayName
  +String? email
  +DateTime? createdAt
  +DateTime? updatedAt
  +UserProfile copyWith()
  +Map<String, Object?> toJson()
}

class "stimmapp::core::data::models::poll.dart::PollOption" {
  +String id
  +String label
  +Map<String, dynamic> toMap()
}

class "stimmapp::core::data::models::poll.dart::Poll" {
  +String id
  +String title
  +String description
  +List<String> tags
  +List<PollOption> options
  +Map<String, int> votes
  +String createdBy
  +DateTime createdAt
  +int totalVotes
  +Poll copyWith()
  {static} +Poll fromFirestore()
  {static} +Map<String, Object?> toFirestore()
}

class "stimmapp::core::data::models::petition.dart::Petition" {
  +String id
  +String title
  +String description
  +List<String> tags
  +int signatureCount
  +String createdBy
  +DateTime createdAt
  +Petition copyWith()
  {static} +Petition fromFirestore()
  {static} +Map<String, Object?> toFirestore()
}

class "stimmapp::core::data::repositories::petition_repository.dart::PetitionRepository" {
  -FirestoreService _fs
  {static} +PetitionRepository create()
  -CollectionReference<Petition> _col()
  +Stream<List<Petition>> list()
  +Stream<Petition?> watch()
  +dynamic get()
  +dynamic createPetition()
  +dynamic sign()
}

"stimmapp::core::data::repositories::petition_repository.dart::PetitionRepository" o-- "stimmapp::core::firebase::firestore::firestore_service.dart::FirestoreService"

class "stimmapp::core::data::repositories::poll_repository.dart::PollRepository" {
  -FirestoreService _fs
  {static} +PollRepository create()
  -CollectionReference<Poll> _col()
  +Stream<List<Poll>> list()
  +Stream<Poll?> watch()
  +dynamic get()
  +dynamic vote()
  +dynamic createPoll()
}

"stimmapp::core::data::repositories::poll_repository.dart::PollRepository" o-- "stimmapp::core::firebase::firestore::firestore_service.dart::FirestoreService"

class "stimmapp::core::data::repositories::user_repository.dart::UserRepository" {
  -FirestoreService _fs
  {static} +UserRepository create()
  -CollectionReference<UserProfile> _col()
  -DocumentReference<UserProfile> _doc()
  +dynamic getById()
  +dynamic upsert()
  +dynamic delete()
  +Stream<UserProfile?> watchById()
  +Stream<List<UserProfile>> watchAll()
}

"stimmapp::core::data::repositories::user_repository.dart::UserRepository" o-- "stimmapp::core::firebase::firestore::firestore_service.dart::FirestoreService"
"stimmapp::core::data::repositories::user_interface.dart::UserInterface" <|-- "stimmapp::core::data::repositories::user_repository.dart::UserRepository"

abstract class "stimmapp::core::data::repositories::user_interface.dart::UserInterface" {
  +dynamic getById()
  +dynamic upsert()
  +dynamic delete()
  +Stream<UserProfile?> watchById()
  +Stream<List<UserProfile>> watchAll()
}

class "stimmapp::core::constants::app_formatters.dart::AppFormatters" {
  {static} +List<TextInputFormatter> lengthLimiting25
  {static} +String dateFormatyyyyMMdd
  {static} +String dateFormatHHmmss
  {static} +String dateFormatMMMMyyyy
}

class "stimmapp::core::constants::app_assets.dart::AppAssets" {
  {static} +String lottieAncientMan
  {static} +String lottieGrafico
  {static} +String lottieSustainable
  {static} +String lottieCheck
  {static} +String lottieCheckmark
  {static} +String lottieCongrats
  {static} +String lottieError
  {static} +String lottieFireworks
  {static} +String lottieGraph
  {static} +String lottieRocket
  {static} +String lottieSnake
  {static} +String lottieYeah
}

class "stimmapp::core::constants::app_dimensions.dart::AppDimensions" {
  {static} +double kPadding5
  {static} +double kPadding10
  {static} +double kPadding15
  {static} +double kPadding25
  {static} +double kPadding50
  {static} +double kAppHorizontalPadding
  {static} +double kBorderRadius3
  {static} +double kBorderRadius10
  {static} +double kBorderRadius25
  {static} +double kMargin2
  {static} +double kMargin3
}

class "stimmapp::core::constants::constants.dart::KConstants" {
  {static} +String themeModeKey
  {static} +String localeKey
  {static} +String appName
  {static} +Color appColor
  {static} +Color lightColor
}

"stimmapp::core::constants::constants.dart::KConstants" o-- "dart::ui::Color"

class "stimmapp::core::constants::storage::user_habit_keys.dart::UserHabitKeys" {
  {static} +String name
  {static} +String progress
  {static} +String count
  {static} +String lastUpdated
  {static} +String date
}

class "stimmapp::core::constants::storage::storage_keys.dart::StorageKeys" {
  {static} +String userHabit
}

class "stimmapp::core::constants::words.dart::Words" {
  {static} +String alert
  {static} +String aboutThisApp
  {static} +String activityHistory
  {static} +String areYouSureYouWantToDeleteYourAccountThisActionIsIrreversible
  {static} +String areYouSureYouWantToLogout
  {static} +String cancel
  {static} +String close
  {static} +String changePassword
  {static} +String consumption
  {static} +String continueNext
  {static} +String currentPassword
  {static} +String dailyHabit
  {static} +String deleted
  {static} +String deleteMyAccount
  {static} +String deletePermanently
  {static} +String email
  {static} +String energy
  {static} +String enterSomething
  {static} +String enterYourEmail
  {static} +String error
  {static} +String exercise
  {static} +String explore
  {static} +String finalNotice
  {static} +String flutterPro
  {static} +String flutterProEmail
  {static} +String getStarted
  {static} +String growthStartsWithin
  {static} +String stimmapp
  {static} +String invalidEmailEntered
  {static} +String lastStep
  {static} +String logout
  {static} +String login
  {static} +String myProfile
  {static} +String nameChangeFailed
  {static} +String newPassword
  {static} +String newUsername
  {static} +String noActivityFound
  {static} +String other
  {static} +String password
  {static} +String passwordChangedSuccessfully
  {static} +String passwordChangeFailed
  {static} +String pleaseCheckYourEmail
  {static} +String products
  {static} +String register
  {static} +String resetPassword
  {static} +String searchTextField
  {static} +String signIn
  {static} +String theWelcomePhrase
  {static} +String settings
  {static} +String travel
  {static} +String updateUsername
  {static} +String usernameChangedSuccessfully
  {static} +String usernameChangeFailed
  {static} +String viewLicenses
  {static} +String welcomeTo
}

class "stimmapp::core::constants::onboarding_words.dart::OnboardingWords" {
  {static} +String howIsYourMindsetTheseDays
  {static} +String whatDoYouNeedPollsHelpWith
  {static} +String defeated
  {static} +String defeatedTitle
  {static} +String defeatedDescription
  {static} +String doubtful
  {static} +String doubtfulTitle
  {static} +String doubtfulDescription
  {static} +String neutral
  {static} +String neutralTitle
  {static} +String neutralDescription
  {static} +String optimistic
  {static} +String optimisticTitle
  {static} +String optimisticDescription
  {static} +String empowered
  {static} +String empoweredTitle
  {static} +String empoweredDescription
  {static} +String offer
  {static} +String offerTitle
  {static} +String offerDescription
  {static} +String traffic
  {static} +String trafficTitle
  {static} +String trafficDescription
  {static} +String sales
  {static} +String salesTitle
  {static} +String salesDescription
}

class "stimmapp::l10n::app_localizations_de.dart::AppLocalizationsDe" {
  +String hintTextTags
  +String language
  +String changeLanguage
  +String english
  +String german
  +String french
  +String settings
  +String alert
  +String aboutThisApp
  +String activityHistory
  +String areYouSureYouWantToDeleteYourAccountThisActionIsIrreversible
  +String areYouSureYouWantToLogout
  +String cancel
  +String close
  +String changePassword
  +String consumption
  +String continueNext
  +String confirm
  +String currentPassword
  +String dailyHabit
  +String deleted
  +String deleteMyAccount
  +String deletePermanently
  +String email
  +String energy
  +String enterSomething
  +String enterYourEmail
  +String error
  +String exercise
  +String explore
  +String finalNotice
  +String flutterPro
  +String flutterProEmail
  +String getStarted
  +String growthStartsWithin
  +String stimmapp
  +String invalidEmailEntered
  +String lastStep
  +String logout
  +String colorTheme
  +String colorMode
  +String login
  +String darkMode
  +String lightMode
  +String systemDefault
  +String myProfile
  +String nameChangeFailed
  +String newPassword
  +String newUsername
  +String noActivityFound
  +String other
  +String password
  +String passwordChangedSuccessfully
  +String passwordChangeFailed
  +String pleaseCheckYourEmail
  +String products
  +String register
  +String resetPassword
  +String searchTextField
  +String signIn
  +String theWelcomePhrase
  +String travel
  +String updateUsername
  +String usernameChangedSuccessfully
  +String usernameChangeFailed
  +String viewLicenses
  +String welcomeTo
  +String petition
  +String petitions
  +String profile
  +String registerAccount
  +String creator
  +String polls
  +String select
  +String noOptions
  +String createPetition
  +String createPoll
  +String developerSandbox
  +String testingWidgetsHere
  +String pleaseSignInFirst
  +String createdPetition
  +String errorCreatingPetition
  +String createdPoll
  +String failedToCreatePoll
  +String petitionDetails
  +String pollDetails
  +String notFound
  +String noData
  +String signed
  +String voted
  +String successfullyLoggedIn
  +String resetPasswordLinkSent
  +String title
  +String enterTitle
  +String titleRequired
  +String titleTooShort
  +String description
  +String enterDescription
  +String descriptionRequired
  +String descriptionTooShort
  +String descriptioRequired
  +String tags
  +String tagsHint
  +String tagsRequired
  +String options
  +String option
  +String optionRequired
  +String addOption
  +String profilePictureUpdated
  +String noImageSelected
  +String signedPetitions
  +String signPetition
  +String entryNotYetImplemented
  +String signatures
  +String supporters
  +String daysLeft
  +String goal
  +String petitionBy
  +String sharePetition
  +String recentPetitions
  +String popularPetitions
  +String myPetitions
  +String victory
  +String petitionSuccessfullySigned
  +String thankYouForSigning
  +String shareThisPetition
  +String updates
  +String reasonsForSigning
  +String comments
  +String addComment
  +String anonymous
  +String editPetition
  +String deletePetition
  +String areYouSureYouWantToDeleteThisPetition
  +String helloAndWelcome()
  +String newMessages()
}

"stimmapp::l10n::app_localizations.dart::AppLocalizations" <|-- "stimmapp::l10n::app_localizations_de.dart::AppLocalizationsDe"

abstract class "stimmapp::l10n::app_localizations.dart::AppLocalizations" {
  +String localeName
  {static} +LocalizationsDelegate<AppLocalizations> delegate
  {static} +List<LocalizationsDelegate<dynamic>> localizationsDelegates
  {static} +List<Locale> supportedLocales
  +String hintTextTags
  +String language
  +String changeLanguage
  +String english
  +String german
  +String french
  +String settings
  +String alert
  +String aboutThisApp
  +String activityHistory
  +String areYouSureYouWantToDeleteYourAccountThisActionIsIrreversible
  +String areYouSureYouWantToLogout
  +String cancel
  +String close
  +String changePassword
  +String consumption
  +String continueNext
  +String confirm
  +String currentPassword
  +String dailyHabit
  +String deleted
  +String deleteMyAccount
  +String deletePermanently
  +String email
  +String energy
  +String enterSomething
  +String enterYourEmail
  +String error
  +String exercise
  +String explore
  +String finalNotice
  +String flutterPro
  +String flutterProEmail
  +String getStarted
  +String growthStartsWithin
  +String stimmapp
  +String invalidEmailEntered
  +String lastStep
  +String logout
  +String colorTheme
  +String colorMode
  +String login
  +String darkMode
  +String lightMode
  +String systemDefault
  +String myProfile
  +String nameChangeFailed
  +String newPassword
  +String newUsername
  +String noActivityFound
  +String other
  +String password
  +String passwordChangedSuccessfully
  +String passwordChangeFailed
  +String pleaseCheckYourEmail
  +String products
  +String register
  +String resetPassword
  +String searchTextField
  +String signIn
  +String theWelcomePhrase
  +String travel
  +String updateUsername
  +String usernameChangedSuccessfully
  +String usernameChangeFailed
  +String viewLicenses
  +String welcomeTo
  +String petition
  +String petitions
  +String profile
  +String registerAccount
  +String creator
  +String polls
  +String select
  +String noOptions
  +String createPetition
  +String createPoll
  +String developerSandbox
  +String testingWidgetsHere
  +String pleaseSignInFirst
  +String createdPetition
  +String errorCreatingPetition
  +String createdPoll
  +String failedToCreatePoll
  +String petitionDetails
  +String pollDetails
  +String notFound
  +String noData
  +String signed
  +String voted
  +String successfullyLoggedIn
  +String resetPasswordLinkSent
  +String title
  +String enterTitle
  +String titleRequired
  +String titleTooShort
  +String description
  +String enterDescription
  +String descriptionRequired
  +String descriptionTooShort
  +String descriptioRequired
  +String tags
  +String tagsHint
  +String tagsRequired
  +String options
  +String option
  +String optionRequired
  +String addOption
  +String profilePictureUpdated
  +String noImageSelected
  +String signedPetitions
  +String signPetition
  +String entryNotYetImplemented
  +String signatures
  +String supporters
  +String daysLeft
  +String goal
  +String petitionBy
  +String sharePetition
  +String recentPetitions
  +String popularPetitions
  +String myPetitions
  +String victory
  +String petitionSuccessfullySigned
  +String thankYouForSigning
  +String shareThisPetition
  +String updates
  +String reasonsForSigning
  +String comments
  +String addComment
  +String anonymous
  +String editPetition
  +String deletePetition
  +String areYouSureYouWantToDeleteThisPetition
  {static} +AppLocalizations? of()
  +String helloAndWelcome()
  +String newMessages()
}

"stimmapp::l10n::app_localizations.dart::AppLocalizations" o-- "flutter::src::widgets::localizations.dart::LocalizationsDelegate<AppLocalizations>"

class "stimmapp::l10n::app_localizations.dart::_AppLocalizationsDelegate" {
  +dynamic load()
  +bool isSupported()
  +bool shouldReload()
}

"flutter::src::widgets::localizations.dart::LocalizationsDelegate" <|-- "stimmapp::l10n::app_localizations.dart::_AppLocalizationsDelegate"

class "stimmapp::l10n::app_localizations_en.dart::AppLocalizationsEn" {
  +String hintTextTags
  +String language
  +String changeLanguage
  +String english
  +String german
  +String french
  +String settings
  +String alert
  +String aboutThisApp
  +String activityHistory
  +String areYouSureYouWantToDeleteYourAccountThisActionIsIrreversible
  +String areYouSureYouWantToLogout
  +String cancel
  +String close
  +String changePassword
  +String consumption
  +String continueNext
  +String confirm
  +String currentPassword
  +String dailyHabit
  +String deleted
  +String deleteMyAccount
  +String deletePermanently
  +String email
  +String energy
  +String enterSomething
  +String enterYourEmail
  +String error
  +String exercise
  +String explore
  +String finalNotice
  +String flutterPro
  +String flutterProEmail
  +String getStarted
  +String growthStartsWithin
  +String stimmapp
  +String invalidEmailEntered
  +String lastStep
  +String logout
  +String colorTheme
  +String colorMode
  +String login
  +String darkMode
  +String lightMode
  +String systemDefault
  +String myProfile
  +String nameChangeFailed
  +String newPassword
  +String newUsername
  +String noActivityFound
  +String other
  +String password
  +String passwordChangedSuccessfully
  +String passwordChangeFailed
  +String pleaseCheckYourEmail
  +String products
  +String register
  +String resetPassword
  +String searchTextField
  +String signIn
  +String theWelcomePhrase
  +String travel
  +String updateUsername
  +String usernameChangedSuccessfully
  +String usernameChangeFailed
  +String viewLicenses
  +String welcomeTo
  +String petition
  +String petitions
  +String profile
  +String registerAccount
  +String creator
  +String polls
  +String select
  +String noOptions
  +String createPetition
  +String createPoll
  +String developerSandbox
  +String testingWidgetsHere
  +String pleaseSignInFirst
  +String createdPetition
  +String errorCreatingPetition
  +String createdPoll
  +String failedToCreatePoll
  +String petitionDetails
  +String pollDetails
  +String notFound
  +String noData
  +String signed
  +String voted
  +String successfullyLoggedIn
  +String resetPasswordLinkSent
  +String title
  +String enterTitle
  +String titleRequired
  +String titleTooShort
  +String description
  +String enterDescription
  +String descriptionRequired
  +String descriptionTooShort
  +String descriptioRequired
  +String tags
  +String tagsHint
  +String tagsRequired
  +String options
  +String option
  +String optionRequired
  +String addOption
  +String profilePictureUpdated
  +String noImageSelected
  +String signedPetitions
  +String signPetition
  +String entryNotYetImplemented
  +String signatures
  +String supporters
  +String daysLeft
  +String goal
  +String petitionBy
  +String sharePetition
  +String recentPetitions
  +String popularPetitions
  +String myPetitions
  +String victory
  +String petitionSuccessfullySigned
  +String thankYouForSigning
  +String shareThisPetition
  +String updates
  +String reasonsForSigning
  +String comments
  +String addComment
  +String anonymous
  +String editPetition
  +String deletePetition
  +String areYouSureYouWantToDeleteThisPetition
  +String helloAndWelcome()
  +String newMessages()
}

"stimmapp::l10n::app_localizations.dart::AppLocalizations" <|-- "stimmapp::l10n::app_localizations_en.dart::AppLocalizationsEn"

class "stimmapp::app::mobile::layout::auth_layout.dart::AuthLayout" {
  +Widget? pageIfNotConnected
  +State<AuthLayout> createState()
}

"stimmapp::app::mobile::layout::auth_layout.dart::AuthLayout" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::layout::auth_layout.dart::AuthLayout"

class "stimmapp::app::mobile::layout::auth_layout.dart::_AuthLayoutState" {
  -dynamic _ensureFuture
  -String? _currentUid
  +Widget build()
  -dynamic _ensureProfileValid()
}

"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::layout::auth_layout.dart::_AuthLayoutState"

class "stimmapp::app::mobile::layout::init_app_layout.dart::InitAppLayout" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::layout::init_app_layout.dart::InitAppLayout"

class "stimmapp::app::mobile::widgets::button_widget.dart::ButtonWidget" {
  +bool isFilled
  +String label
  +dynamic Function()? callback
  +Widget build()
}

"stimmapp::app::mobile::widgets::button_widget.dart::ButtonWidget" o-- "null::dynamic Function()"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::widgets::button_widget.dart::ButtonWidget"

class "stimmapp::app::mobile::widgets::navbar_widget.dart::NavbarWidget" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::widgets::navbar_widget.dart::NavbarWidget"

class "stimmapp::app::mobile::widgets::unaffected_child_widget.dart::UnaffectedChildWidget" {
  +Widget child
  +Widget build()
}

"stimmapp::app::mobile::widgets::unaffected_child_widget.dart::UnaffectedChildWidget" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::widgets::unaffected_child_widget.dart::UnaffectedChildWidget"

class "stimmapp::app::mobile::widgets::list_tile_widget.dart::ListTileWidget" {
  +Widget title
  +List<Widget>? widgets
  +Widget? action
  +Widget build()
}

"stimmapp::app::mobile::widgets::list_tile_widget.dart::ListTileWidget" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::widgets::list_tile_widget.dart::ListTileWidget"

class "stimmapp::app::mobile::widgets::search_text_field.dart::SearchTextField" {
  +void Function(String) onChanged
  +String hint
  +Duration debounce
  +State<SearchTextField> createState()
}

"stimmapp::app::mobile::widgets::search_text_field.dart::SearchTextField" o-- "flutter::src::foundation::basic_types.dart::void Function(String)"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::widgets::search_text_field.dart::SearchTextField"

class "stimmapp::app::mobile::widgets::search_text_field.dart::_SearchTextFieldState" {
  -TextEditingController _controller
  -Timer? _timer
  +void dispose()
  -void _onChanged()
  +Widget build()
}

"stimmapp::app::mobile::widgets::search_text_field.dart::_SearchTextFieldState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"stimmapp::app::mobile::widgets::search_text_field.dart::_SearchTextFieldState" o-- "dart::async::Timer"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::widgets::search_text_field.dart::_SearchTextFieldState"

class "stimmapp::app::mobile::widgets::neon_padding_widget.dart::NeonPaddingWidget" {
  +String? title
  +String? label1
  +Widget? child
  +bool isCentered
  +Widget build()
}

"stimmapp::app::mobile::widgets::neon_padding_widget.dart::NeonPaddingWidget" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::widgets::neon_padding_widget.dart::NeonPaddingWidget"

class "stimmapp::app::mobile::widgets::profile_widget.dart::ProfileWidget" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::widgets::profile_widget.dart::ProfileWidget"

class "stimmapp::app::mobile::widgets::container_widget.dart::ContainerWidget" {
  +String title
  +String description
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::widgets::container_widget.dart::ContainerWidget"

class "stimmapp::app::mobile::widgets::hero_widget.dart::HeroWidget" {
  +String? title
  +Widget? nextPage
  +Widget build()
}

"stimmapp::app::mobile::widgets::hero_widget.dart::HeroWidget" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::widgets::hero_widget.dart::HeroWidget"

class "stimmapp::app::mobile::widgets::selection_notifier_dialog.dart::SelectionNotifierDialog" {
  +ValueNotifier<T?> notifier
  +List<T> options
  +String Function(BuildContext, T) optionLabel
  +String? title
  +String? confirmLabel
  +String? cancelLabel
  +void Function(T?)? onConfirm
  +State<SelectionNotifierDialog<T>> createState()
}

"stimmapp::app::mobile::widgets::selection_notifier_dialog.dart::SelectionNotifierDialog" o-- "flutter::src::foundation::change_notifier.dart::ValueNotifier<T>"
"stimmapp::app::mobile::widgets::selection_notifier_dialog.dart::SelectionNotifierDialog" o-- "null::String Function(BuildContext, T)"
"stimmapp::app::mobile::widgets::selection_notifier_dialog.dart::SelectionNotifierDialog" o-- "null::void Function(T)"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::widgets::selection_notifier_dialog.dart::SelectionNotifierDialog"

class "stimmapp::app::mobile::widgets::selection_notifier_dialog.dart::_SelectionNotifierDialogState" {
  -T? _selected
  +void initState()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::widgets::selection_notifier_dialog.dart::_SelectionNotifierDialogState"

class "stimmapp::app::mobile::pages::main::onboarding::reset_password_page.dart::ResetPasswordPage" {
  +String email
  +State<ResetPasswordPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::onboarding::reset_password_page.dart::ResetPasswordPage"

class "stimmapp::app::mobile::pages::main::onboarding::reset_password_page.dart::_ResetPasswordPageState" {
  +TextEditingController controllerEmail
  +GlobalKey<FormState> formKey
  +String errorMessage
  +void initState()
  +void dispose()
  +void resetPassword()
  +Widget build()
}

"stimmapp::app::mobile::pages::main::onboarding::reset_password_page.dart::_ResetPasswordPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"stimmapp::app::mobile::pages::main::onboarding::reset_password_page.dart::_ResetPasswordPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::onboarding::reset_password_page.dart::_ResetPasswordPageState"

class "stimmapp::app::mobile::pages::main::onboarding::welcome_page.dart::WelcomePage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::pages::main::onboarding::welcome_page.dart::WelcomePage"

class "stimmapp::app::mobile::pages::main::onboarding::onboarding_page.dart::OnboardingPage" {
  +State<OnboardingPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::onboarding::onboarding_page.dart::OnboardingPage"

class "stimmapp::app::mobile::pages::main::onboarding::onboarding_page.dart::_OnboardingPageState" {
  -GlobalKey<FormState> _formKey
  +String errorMessage
  -double _progress
  +void register()
  +void popPage()
  +void registerWithPostId()
  +Widget build()
}

"stimmapp::app::mobile::pages::main::onboarding::onboarding_page.dart::_OnboardingPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::onboarding::onboarding_page.dart::_OnboardingPageState"

class "stimmapp::app::mobile::pages::main::onboarding::login_page.dart::LoginPage" {
  +State<LoginPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::onboarding::login_page.dart::LoginPage"

class "stimmapp::app::mobile::pages::main::onboarding::login_page.dart::_LoginPageState" {
  +TextEditingController controllerEm
  +TextEditingController controllerPw
  +GlobalKey<FormState> formKey
  +String errorMessage
  +void dispose()
  +void signIn()
  +void popPage()
  +Widget build()
}

"stimmapp::app::mobile::pages::main::onboarding::login_page.dart::_LoginPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"stimmapp::app::mobile::pages::main::onboarding::login_page.dart::_LoginPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::onboarding::login_page.dart::_LoginPageState"

class "stimmapp::app::mobile::pages::main::profile::delete_account_page.dart::DeleteAccountPage" {
  +State<DeleteAccountPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::profile::delete_account_page.dart::DeleteAccountPage"

class "stimmapp::app::mobile::pages::main::profile::delete_account_page.dart::_DeleteAccountPageState" {
  +GlobalKey<FormState> formKey
  +TextEditingController controllerEmail
  +TextEditingController controllerPassword
  +String errorMessage
  +void popUntilLast()
  +void deleteAccount()
  +void showSnackBar()
  +void dispose()
  +Widget build()
}

"stimmapp::app::mobile::pages::main::profile::delete_account_page.dart::_DeleteAccountPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"stimmapp::app::mobile::pages::main::profile::delete_account_page.dart::_DeleteAccountPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::profile::delete_account_page.dart::_DeleteAccountPageState"

class "stimmapp::app::mobile::pages::main::profile::update_username_page.dart::UpdateUsernamePage" {
  +State<UpdateUsernamePage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::profile::update_username_page.dart::UpdateUsernamePage"

class "stimmapp::app::mobile::pages::main::profile::update_username_page.dart::_UpdateUsernamePageState" {
  +TextEditingController controllerUsername
  +GlobalKey<FormState> formKey
  +String errorMessage
  +void dispose()
  +void updateUsername()
  +Widget build()
}

"stimmapp::app::mobile::pages::main::profile::update_username_page.dart::_UpdateUsernamePageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"stimmapp::app::mobile::pages::main::profile::update_username_page.dart::_UpdateUsernamePageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::profile::update_username_page.dart::_UpdateUsernamePageState"

class "stimmapp::app::mobile::pages::main::profile::user_history.dart::UserHistoryPage" {
  +State<UserHistoryPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::profile::user_history.dart::UserHistoryPage"

class "stimmapp::app::mobile::pages::main::profile::user_history.dart::_UserHistoryPageState" {
  -dynamic _historyFuture
  +void initState()
  -dynamic _fetchUserHistory()
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::profile::user_history.dart::_UserHistoryPageState"

class "stimmapp::app::mobile::pages::main::profile::widgets::profile_widget.dart::ProfileWidget" {
  +Widget build()
  +void showSnackBarFailure()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::pages::main::profile::widgets::profile_widget.dart::ProfileWidget"

class "stimmapp::app::mobile::pages::main::profile::change_password_page.dart::ChangePasswordPage" {
  +State<ChangePasswordPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::profile::change_password_page.dart::ChangePasswordPage"

class "stimmapp::app::mobile::pages::main::profile::change_password_page.dart::_ChangePasswordPageState" {
  +TextEditingController controllerCurrentPassword
  +TextEditingController controllerNewPassword
  +GlobalKey<FormState> formKey
  +String errorMessage
  +void dispose()
  +void updatePassword()
  +Widget build()
}

"stimmapp::app::mobile::pages::main::profile::change_password_page.dart::_ChangePasswordPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"stimmapp::app::mobile::pages::main::profile::change_password_page.dart::_ChangePasswordPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::profile::change_password_page.dart::_ChangePasswordPageState"

class "stimmapp::app::mobile::pages::main::profile::change_profile_picture_page.dart::ChangeProfilePicturePage" {
  +State<ChangeProfilePicturePage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::profile::change_profile_picture_page.dart::ChangeProfilePicturePage"

class "stimmapp::app::mobile::pages::main::profile::change_profile_picture_page.dart::_ChangeProfilePicturePageState" {
  -File? _imageFile
  -bool _uploading
  -double _progress
  -ImagePicker _picker
  -StreamSubscription<TaskSnapshot>? _uploadSub
  -dynamic _pickImage()
  -dynamic _removeImage()
  -dynamic _uploadAndSave()
  +void dispose()
  +Widget build()
}

"stimmapp::app::mobile::pages::main::profile::change_profile_picture_page.dart::_ChangeProfilePicturePageState" o-- "dart::io::File"
"stimmapp::app::mobile::pages::main::profile::change_profile_picture_page.dart::_ChangeProfilePicturePageState" o-- "image_picker::image_picker.dart::ImagePicker"
"stimmapp::app::mobile::pages::main::profile::change_profile_picture_page.dart::_ChangeProfilePicturePageState" o-- "dart::async::StreamSubscription<TaskSnapshot>"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::profile::change_profile_picture_page.dart::_ChangeProfilePicturePageState"

class "stimmapp::app::mobile::pages::main::profile::profile_page.dart::ProfilePage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::pages::main::profile::profile_page.dart::ProfilePage"

class "stimmapp::app::mobile::pages::main::profile::signed_petitions_page.dart::SignedPetitionsPage" {
  -Stream<QuerySnapshot<Map<String, dynamic>>> _signedPetitionsStream()
  +Widget build()
  {static} -String _formatDate()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::pages::main::profile::signed_petitions_page.dart::SignedPetitionsPage"

class "stimmapp::app::mobile::pages::main::home::polls::polls_page.dart::PollsPage" {
  +State<PollsPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::home::polls::polls_page.dart::PollsPage"

class "stimmapp::app::mobile::pages::main::home::polls::polls_page.dart::_PollsPageState" {
  -PollRepository _repo
  -String _query
  +Widget build()
}

"stimmapp::app::mobile::pages::main::home::polls::polls_page.dart::_PollsPageState" o-- "stimmapp::core::data::repositories::poll_repository.dart::PollRepository"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::home::polls::polls_page.dart::_PollsPageState"

class "stimmapp::app::mobile::pages::main::home::polls::poll_detail_page.dart::PollDetailPage" {
  +String id
  +State<PollDetailPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::home::polls::poll_detail_page.dart::PollDetailPage"

class "stimmapp::app::mobile::pages::main::home::polls::poll_detail_page.dart::_PollDetailPageState" {
  -String? _selectedOptionId
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::home::polls::poll_detail_page.dart::_PollDetailPageState"

class "stimmapp::app::mobile::pages::main::home::home_navigation_config.dart::MainPageConfig" {
  +Widget page
  +String title
  +IconData icon
}

"stimmapp::app::mobile::pages::main::home::home_navigation_config.dart::MainPageConfig" o-- "flutter::src::widgets::framework.dart::Widget"
"stimmapp::app::mobile::pages::main::home::home_navigation_config.dart::MainPageConfig" o-- "flutter::src::widgets::icon_data.dart::IconData"

class "stimmapp::app::mobile::pages::main::home::widget_tree.dart::WidgetTree" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::pages::main::home::widget_tree.dart::WidgetTree"

class "stimmapp::app::mobile::pages::main::home::petitions::petitions_page.dart::PetitionsPage" {
  +State<PetitionsPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::home::petitions::petitions_page.dart::PetitionsPage"

class "stimmapp::app::mobile::pages::main::home::petitions::petitions_page.dart::_PetitionsPageState" {
  -PetitionRepository _repo
  -String _query
  +Widget build()
}

"stimmapp::app::mobile::pages::main::home::petitions::petitions_page.dart::_PetitionsPageState" o-- "stimmapp::core::data::repositories::petition_repository.dart::PetitionRepository"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::home::petitions::petitions_page.dart::_PetitionsPageState"

class "stimmapp::app::mobile::pages::main::home::petitions::petition_detail_page.dart::PetitionDetailPage" {
  +String id
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::pages::main::home::petitions::petition_detail_page.dart::PetitionDetailPage"

class "stimmapp::app::mobile::pages::main::home::creator::creator_page.dart::CreatorPage" {
  +State<CreatorPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::home::creator::creator_page.dart::CreatorPage"

class "stimmapp::app::mobile::pages::main::home::creator::creator_page.dart::_CreatorPageState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::home::creator::creator_page.dart::_CreatorPageState"

class "stimmapp::app::mobile::pages::main::home::creator::poll_creator_page.dart::PollCreatorPage" {
  +State<PollCreatorPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::home::creator::poll_creator_page.dart::PollCreatorPage"

class "stimmapp::app::mobile::pages::main::home::creator::poll_creator_page.dart::_PollCreatorPageState" {
  -GlobalKey<FormState> _formKey
  -TextEditingController _titleController
  -TextEditingController _descriptionController
  -TextEditingController _tagsController
  -List<TextEditingController> _optionControllers
  -PollRepository _repository
  -bool _isLoading
  -Uuid _uuid
  +void dispose()
  -void _addOption()
  -void _removeOption()
  -dynamic _createPoll()
  +Widget build()
}

"stimmapp::app::mobile::pages::main::home::creator::poll_creator_page.dart::_PollCreatorPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"stimmapp::app::mobile::pages::main::home::creator::poll_creator_page.dart::_PollCreatorPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"stimmapp::app::mobile::pages::main::home::creator::poll_creator_page.dart::_PollCreatorPageState" o-- "stimmapp::core::data::repositories::poll_repository.dart::PollRepository"
"stimmapp::app::mobile::pages::main::home::creator::poll_creator_page.dart::_PollCreatorPageState" o-- "uuid::uuid.dart::Uuid"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::home::creator::poll_creator_page.dart::_PollCreatorPageState"

class "stimmapp::app::mobile::pages::main::home::creator::petition_creator_page.dart::PetitionCreatorPage" {
  +State<PetitionCreatorPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::home::creator::petition_creator_page.dart::PetitionCreatorPage"

class "stimmapp::app::mobile::pages::main::home::creator::petition_creator_page.dart::_PetitionCreatorPageState" {
  -GlobalKey<FormState> _formKey
  -TextEditingController _titleController
  -TextEditingController _descriptionController
  -TextEditingController _tagsController
  -PetitionRepository _repository
  -bool _isLoading
  +void dispose()
  -dynamic _createPetition()
  +Widget build()
}

"stimmapp::app::mobile::pages::main::home::creator::petition_creator_page.dart::_PetitionCreatorPageState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"stimmapp::app::mobile::pages::main::home::creator::petition_creator_page.dart::_PetitionCreatorPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"stimmapp::app::mobile::pages::main::home::creator::petition_creator_page.dart::_PetitionCreatorPageState" o-- "stimmapp::core::data::repositories::petition_repository.dart::PetitionRepository"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::home::creator::petition_creator_page.dart::_PetitionCreatorPageState"

class "stimmapp::app::mobile::pages::main::settings::settings_page.dart::SettingsPage" {
  +String title
  +State<SettingsPage> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::pages::main::settings::settings_page.dart::SettingsPage"

class "stimmapp::app::mobile::pages::main::settings::settings_page.dart::_SettingsPageState" {
  +TextEditingController controller
  +bool isChecked
  +bool isSwitched
  +double sliderValue
  +String? menuItem
  +void popUntilLast()
  +Widget build()
}

"stimmapp::app::mobile::pages::main::settings::settings_page.dart::_SettingsPageState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::pages::main::settings::settings_page.dart::_SettingsPageState"

class "stimmapp::app::mobile::pages::others::outdated_page.dart::OutdatedPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::pages::others::outdated_page.dart::OutdatedPage"

class "stimmapp::app::mobile::pages::others::app_loading_page.dart::AppLoadingPage" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::pages::others::app_loading_page.dart::AppLoadingPage"

class "stimmapp::app::mobile::scaffolds::app_bar_scaffold.dart::AppBarScaffold" {
  +String title
  +List<Widget>? actions
  +Widget child
  +State<AppBarScaffold> createState()
}

"stimmapp::app::mobile::scaffolds::app_bar_scaffold.dart::AppBarScaffold" o-- "flutter::src::widgets::framework.dart::Widget"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "stimmapp::app::mobile::scaffolds::app_bar_scaffold.dart::AppBarScaffold"

class "stimmapp::app::mobile::scaffolds::app_bar_scaffold.dart::_AppBarScaffoldState" {
  +double collapsedBarHeight
  +double expandedBarHeight
  +ScrollController scrollController
  +bool isCollapsed
  +bool didAddFeedback
  +Widget build()
}

"stimmapp::app::mobile::scaffolds::app_bar_scaffold.dart::_AppBarScaffoldState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::State" <|-- "stimmapp::app::mobile::scaffolds::app_bar_scaffold.dart::_AppBarScaffoldState"

class "stimmapp::app::mobile::scaffolds::app_bottom_bar_buttons.dart::AppBottomBarButtons" {
  +List<Widget> buttons
  +Widget body
  +PreferredSizeWidget? appBar
  +Widget build()
}

"stimmapp::app::mobile::scaffolds::app_bottom_bar_buttons.dart::AppBottomBarButtons" o-- "flutter::src::widgets::framework.dart::Widget"
"stimmapp::app::mobile::scaffolds::app_bottom_bar_buttons.dart::AppBottomBarButtons" o-- "flutter::src::widgets::preferred_size.dart::PreferredSizeWidget"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::scaffolds::app_bottom_bar_buttons.dart::AppBottomBarButtons"

class "stimmapp::app::mobile::scaffolds::app_padding_scaffold.dart::AppPaddingScaffold" {
  +Widget? child
  +List<Widget>? children
  +MainAxisAlignment mainAxisAlignment
  +CrossAxisAlignment crossAxisAlignment
  +MainAxisSize mainAxisSize
  +Widget build()
}

"stimmapp::app::mobile::scaffolds::app_padding_scaffold.dart::AppPaddingScaffold" o-- "flutter::src::widgets::framework.dart::Widget"
"stimmapp::app::mobile::scaffolds::app_padding_scaffold.dart::AppPaddingScaffold" o-- "flutter::src::rendering::flex.dart::MainAxisAlignment"
"stimmapp::app::mobile::scaffolds::app_padding_scaffold.dart::AppPaddingScaffold" o-- "flutter::src::rendering::flex.dart::CrossAxisAlignment"
"stimmapp::app::mobile::scaffolds::app_padding_scaffold.dart::AppPaddingScaffold" o-- "flutter::src::rendering::flex.dart::MainAxisSize"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "stimmapp::app::mobile::scaffolds::app_padding_scaffold.dart::AppPaddingScaffold"


@enduml